pipeline {
    agent any
    options {
        buildDiscarder(logRotator(numToKeepStr:'5'))
    }

    environment {
        PATH = "/usr/local/bin:$PATH"
        // Use a temp directory inside the workspace or /tmp for Docker config
        DOCKER_CONFIG = "${env.WORKSPACE}/.docker"
        DOCKERHUB_CREDENTIALS = credentials('8e1dfa67-ff83-4c76-99f4-f53d421be9de')
        IMAGE_NAME = 'customer_portal'
    }

    stages {
        stage('Stop and Cleanup') {
            steps {
                sh '''
                echo "stopping container"
                docker ps -q --filter "name=mysql_portal" | xargs -r docker stop
                docker ps -aq --filter "name=mysql_portal" | xargs -r docker rm
                docker ps -q --filter "name=customer_portal" | xargs -r docker stop
                docker ps -aq --filter "name=customer_portal" | xargs -r docker rm
                '''
            }
        }
        stage('Login DockerHub') {
            steps {
                sh '''
                mkdir -p "$DOCKER_CONFIG"
                echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin docker.io
                '''
            }
        }
        stage('List Files') {
            steps {
                sh 'ls -al'
            }
        }

        stage('Build MySql Image') {
            steps {
                sh 'docker build -t tanujsahoo/mysql_portal:${BUILD_NUMBER} -f ./customer/MySqlDockerfile .'
            }
        }
        stage('Build WebApp Image') {
            steps {
                sh 'docker build -t tanujsahoo/customer_portal:${BUILD_NUMBER} -f ./customer/Dockerfile .'
            }
        }

        //  stage('Install Dependency') {
        //     steps {
        //         sh 'RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer --version=2.4.4'
        //     }
        // }

        stage('Run Composer and Unit Tests') {
            steps {
                dir("customer/src") {
                               /** echo "stopping container"
                                composer install --ignore-platform-req=ext-gd  
                                chmod -R 777 vendor
                                mkdir -p storage/framework/views 
                                ls -ld bootstrap/cache
                                mkdir -p bootstrap/cache
                                chmod -R 775 bootstrap/cache
                                chmod -R 777 storage 
                        composer dump-autoload **/
                sh '''
                        set -e
                        
                        echo "Ensuring necessary directories exist"
                        mkdir -p storage/framework/views
                        mkdir -p bootstrap/cache
                        
                        echo "Setting permissions"
                        chmod -R 775 bootstrap/cache
                        chmod -R 775 storage
                        echo "VIEW_COMPILED_PATH: $VIEW_COMPILED_PATH"
                        # Avoid chmod 777 vendor unless absolutely necessary
                        
                        ls -ld bootstrap/cache storage/framework/views
                        
                        echo "Clearing Laravel caches"
                        php artisan cache:clear
                        php artisan config:clear
                        php artisan view:clear
                        
                        echo "Installing composer dependencies"
                        composer install --ignore-platform-req=ext-gd
                        
                        echo "Dumping autoload"
                        composer dump-autoload
                    '''
                }
            }
        }
        stage('Unit Testing') {
            steps {
                sh """
                    docker exec customer_php php ./vendor/phpunit/phpunit/phpunit /var/www/html/tests/Unit
                """
            }
        }

        // stage('Integration Testing') {
        //     steps {
        //         sh """
        //             docker exec customer_php php ./vendor/phpunit/phpunit/phpunit /var/www/html/tests/Feature
        //         """
        //     }
        // }

        stage('Creating Tag') {
            steps {
                sh 'docker tag tanujsahoo/mysql_portal:${BUILD_NUMBER} tanujsahoo/mysql_portal:${BUILD_NUMBER}'
                sh 'docker tag tanujsahoo/customer_portal:${BUILD_NUMBER} tanujsahoo/customer_portal:${BUILD_NUMBER}'
            }
        }
        stage('Push Build') {
            steps {
                sh '''
                docker push tanujsahoo/mysql_portal:${BUILD_NUMBER}
                docker push tanujsahoo/customer_portal:${BUILD_NUMBER}
                '''
            }
        }
    }
     post {
            always {
                    // Cleanup Docker config to avoid leaving tokens behind
                    sh 'rm -rf "$DOCKER_CONFIG"'
            }
        }
}